version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn
      - run: echo "cp config file"
      - run: cp ./src/config.example.js ./src/config.js
      - run: echo "yarn run build"
      - run: yarn run build
      - run:
          name: Fix ssh Could not resolve hostname
          command: |
            ssh-keyscan 45.32.102.151 >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - '7c:3e:38:77:58:00:50:0f:95:f8:97:17:66:86:0f:e3'
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@45.32.102.151 'sh deploy-frontend.sh'
