version: 2
jobs:
  build:
    docker:
      - image: circleci/node:15.1
    steps:
      - checkout
      - run: echo "yarn installing"
      - run: yarn
      - run: echo "cp config file"
      - run: cp ./src/config.example.js ./src/config.js
      - run: echo "yarn run build"
      - run: yarn run build
  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploy Over SSH
          command: |
            ssh root@45.77.246.99:9000 'sh deploy-frontend.sh'
